import type { Product } from '@/types';
import { PlaceHolderImages } from './placeholder-images';

const findImage = (id: string) => {
  const img = PlaceHolderImages.find((p) => p.id === id);
  if (!img) {
    return {
      imageUrl: "https://picsum.photos/seed/placeholder/400/500",
      imageHint: "placeholder image"
    };
  }
  return {
    imageUrl: img.imageUrl,
    imageHint: img.imageHint,
  };
};

export const mockProducts: Product[] = [
  {
    id: '1',
    name: "Men's Casual Shirt",
    image: findImage('mens-shirt').imageUrl,
    imageHint: findImage('mens-shirt').imageHint,
    rating: 4.2,
    gender: 'male',
    price: 799,
    stock: 20,
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'A comfortable cotton casual shirt, perfect for everyday wear. Features a classic button-down collar and a relaxed fit.',
    tags: ['new'],
    createdAt: new Date(new Date().setDate(new Date().getDate()-1)).toISOString(),
  },
  {
    id: '2',
    name: "Women's Floral Dress",
    image: findImage('women-dress').imageUrl,
    imageHint: findImage('women-dress').imageHint,
    rating: 4.6,
    gender: 'female',
    price: 1299,
    stock: 15,
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'An elegant floral midi dress made from lightweight fabric. Ideal for summer outings and special occasions.',
    tags: ['trending', 'best-seller'],
    createdAt: new Date(new Date().setDate(new Date().getDate()-5)).toISOString(),
  },
  {
    id: '3',
    name: 'Unisex Hoodie',
    image: findImage('unisex-hoodie').imageUrl,
    imageHint: findImage('unisex-hoodie').imageHint,
    rating: 4.4,
    gender: 'unisex',
    price: 1599,
    stock: 30,
    sizes: ['M', 'L', 'XL'],
    description: 'A warm and cozy hoodie for all genders. Made with soft fleece material, it includes a drawstring hood and a large front pocket.',
    createdAt: new Date(new Date().setDate(new Date().getDate()-10)).toISOString(),
  },
  {
    id: '4',
    name: "Women's Ethnic Kurta",
    image: findImage('women-kurta').imageUrl,
    imageHint: findImage('women-kurta').imageHint,
    rating: 4.8,
    gender: 'female',
    price: 999,
    stock: 25,
    sizes: ['S', 'M', 'L'],
    description: 'A beautifully designed ethnic kurta for women. Features intricate embroidery and a comfortable fit for festive occasions.',
    tags: ['new'],
    createdAt: new Date(new Date().setDate(new Date().getDate()-2)).toISOString(),
  },
  {
    id: '5',
    name: "Men's Slim-Fit Jeans",
    image: findImage('men-jeans').imageUrl,
    imageHint: findImage('men-jeans').imageHint,
    rating: 4.3,
    gender: 'male',
    price: 1499,
    stock: 18,
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Modern slim-fit jeans for men, made from stretchable denim for maximum comfort and style.',
    tags: ['best-seller'],
    createdAt: new Date(new Date().setDate(new Date().getDate()-20)).toISOString(),
  },
  {
    id: '6',
    name: 'Elegant Silk Saree',
    image: findImage('women-saree').imageUrl,
    imageHint: findImage('women-saree').imageHint,
    rating: 4.9,
    gender: 'female',
    price: 2499,
    stock: 10,
    sizes: ['M'],
    description: 'A luxurious silk saree with a traditional design, perfect for weddings and formal events. Comes with a matching blouse piece.',
    tags: ['trending'],
    createdAt: new Date(new Date().setDate(new Date().getDate()-15)).toISOString(),
  },
    {
    id: '7',
    name: "Men's Ethnic Kurta",
    image: findImage('men-kurta').imageUrl,
    imageHint: findImage('men-kurta').imageHint,
    rating: 4.5,
    gender: 'male',
    price: 1199,
    stock: 22,
    sizes: ['M', 'L', 'XL'],
    description: 'A stylish and comfortable ethnic kurta for men, suitable for cultural events and celebrations.',
    tags: ['new'],
    createdAt: new Date(new Date().setDate(new Date().getDate()-3)).toISOString(),
  },
  {
    id: '8',
    name: 'Casual V-Neck Top',
    image: findImage('women-top').imageUrl,
    imageHint: findImage('women-top').imageHint,
    rating: 4.1,
    gender: 'female',
    price: 699,
    stock: 40,
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'A versatile and casual V-neck top for women, perfect for pairing with jeans or skirts.',
    createdAt: new Date(new Date().setDate(new Date().getDate()-8)).toISOString(),
  },
  {
    id: '9',
    name: 'Graphic Print T-Shirt',
    image: findImage('men-tshirt').imageUrl,
    imageHint: findImage('men-tshirt').imageHint,
    rating: 4.0,
    gender: 'male',
    price: 499,
    stock: 50,
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'A trendy graphic print t-shirt for men, made from 100% cotton for a soft feel.',
    createdAt: new Date(new Date().setDate(new Date().getDate()-4)).toISOString(),
  },
  {
    id: '10',
    name: "Women's High-Waist Jeans",
    image: findImage('women-jeans').imageUrl,
    imageHint: findImage('women-jeans').imageHint,
    rating: 4.7,
    gender: 'female',
    price: 1699,
    stock: 12,
    sizes: ['S', 'M', 'L'],
    description: 'Fashionable high-waist jeans for women that offer a flattering fit and all-day comfort.',
    tags: ['best-seller'],
    createdAt: new Date(new Date().setDate(new Date().getDate()-30)).toISOString(),
  },
  {
    id: '11',
    name: "Chic A-Line Dress",
    image: findImage('women-aline-dress').imageUrl,
    imageHint: findImage('women-aline-dress').imageHint,
    rating: 4.5,
    gender: 'female',
    price: 1899,
    stock: 14,
    sizes: ['S', 'M', 'L'],
    description: 'A classic A-line dress with a modern twist. Perfect for both casual and semi-formal events.',
    tags: ['new', 'trending'],
    createdAt: new Date(new Date().setDate(new Date().getDate()-6)).toISOString(),
  },
  {
    id: '12',
    name: 'Summer Maxi Dress',
    image: findImage('women-maxi-dress').imageUrl,
    imageHint: findImage('women-maxi-dress').imageHint,
    rating: 4.6,
    gender: 'female',
    price: 2199,
    stock: 20,
    sizes: ['XS', 'S', 'M'],
    description: 'A light and airy maxi dress, perfect for warm summer days. Features a vibrant print and a comfortable, flowing fit.',
    tags: ['trending'],
    createdAt: new Date(new Date().setDate(new Date().getDate()-12)).toISOString(),
  },
  {
    id: '13',
    name: 'Velvet Party Dress',
    image: findImage('women-velvet-dress').imageUrl,
    imageHint: findImage('women-velvet-dress').imageHint,
    rating: 4.8,
    gender: 'female',
    price: 2999,
    stock: 8,
    sizes: ['S', 'M'],
    description: 'An elegant velvet dress that is sure to turn heads at any party. Features a sophisticated silhouette and a luxurious feel.',
    tags: ['best-seller'],
    createdAt: new Date(new Date().setDate(new Date().getDate()-25)).toISOString(),
  },
  {
    id: '14',
    name: "Men's Formal Blazer",
    image: findImage('men-blazer').imageUrl,
    imageHint: findImage('men-blazer').imageHint,
    rating: 4.7,
    gender: 'male',
    price: 3499,
    stock: 15,
    sizes: ['M', 'L', 'XL'],
    description: 'A sophisticated formal blazer, perfect for business meetings and evening events. Crafted from premium fabric for a sharp look.',
    tags: ['new'],
    createdAt: new Date(new Date().setDate(new Date().getDate()-4)).toISOString(),
  },
  {
    id: '15',
    name: "Men's Classic Polo",
    image: findImage('men-polo').imageUrl,
    imageHint: findImage('men-polo').imageHint,
    rating: 4.5,
    gender: 'male',
    price: 899,
    stock: 25,
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'A timeless polo t-shirt that combines comfort and style. Made from breathable pique cotton, it\'s a wardrobe essential.',
    tags: ['best-seller'],
    createdAt: new Date(new Date().setDate(new Date().getDate()-40)).toISOString(),
  },
  {
    id: '16',
    name: 'Traditional Sherwani',
    image: findImage('men-sherwani').imageUrl,
    imageHint: findImage('men-sherwani').imageHint,
    rating: 4.9,
    gender: 'male',
    price: 7999,
    stock: 7,
    sizes: ['M', 'L', 'XL'],
    description: 'An exquisitely crafted traditional sherwani for weddings and grand celebrations. Features intricate embroidery and luxurious fabric.',
    tags: ['trending'],
    createdAt: new Date(new Date().setDate(new Date().getDate()-18)).toISOString(),
  },
];
